;=========================
; Addressing Modes
;=========================

.MODEL SMALL
 
.STACK 100H

.DATA

; declare variables here

.CODE
MAIN PROC

; initialize DS

MOV AX,@DATA
MOV DS,AX
 
; enter your code here

;=========================
; INVALID INSTRUCTION FORMATS:
; -> OPERATOR IMMEDIATE, REGISTER   ; Destination cannot be an immediate value.
; -> OPERATOR IMMEDIATE, IMMEDIATE  ; Both operands cannot be immediate values.
;=========================

;=========================  

; ADDRESSING MODES
; -> THE 8086 PROVIDES 7 TYPES OF ADDRESSING MODES
;    FOR ACCESSING DATA.

;=========================
   
;=========================
; (1) IMMEDIATE ADDRESSING 

; -> SOURCE IS A CONSTANT VALUE 
;=========================

ADD AX, 5H
          
          
 
;=========================
; (2) DIRECT ADDRESSING  

; -> THE OFFSET ADDRESS OF THE OPERAND IS SPECIFIED DIRECTLY IN THE INSTRUCTION.
; -> BY DEFAULT, THE OPERAND IS ACCESSED FROM THE DATA SEGMENT (DS).
;=========================

MOV AX, [1234H] ; READ
MOV [1234H], AX ; WRITE 
              
              

;=========================
; (3) REGISTER DIRECT ADDRESSING 

; -> NO MEMORY ADDRESS IS INVOLVED.
; -> THE SOURCE REGISTER CONTAINS THE ACTUAL DATA (OPERAND).
;=========================

MOV AX, BX


 
;=========================
; (4) REGISTER INDIRECT ADDRESSING 

; -> THE REGISTER HOLDS THE OFFSET ADDRESS OF THE OPERAND.
; -> THE CPU ACCESSES THE OPERAND FROM MEMORY USING THAT OFFSET.
; -> THE SEGMENT REGISTER (DS OR SS) DETERMINES THE SEGMENT ADDRESS.
;=========================

MOV AX, [BX]


 
;=========================
; (5) BASE RELATIVE ADDRESSING 

; -> THE EFFECTIVE ADDRESS (OFFSET) IS CALCULATED AS:
;    BASE REGISTER + DISPLACEMENT.
; -> THE CPU ACCESSES THE OPERAND FROM MEMORY USING THIS OFFSET.
; -> BY DEFAULT, DS IS USED WITH BX AND SS IS USED WITH BP.
;=========================        

MOV AX, [BX + 0100H]   



;=========================
; (6) BASE + INDEX ADDRESSING 

; -> THE EFFECTIVE ADDRESS (OFFSET) IS CALCULATED AS:
;    BASE REGISTER + INDEX REGISTER.
; -> THE CPU ACCESSES THE OPERAND FROM MEMORY USING THIS OFFSET.
; -> IF BX IS THE BASE REGISTER, THE DEFAULT SEGMENT IS DS.
; -> IF BP IS THE BASE REGISTER, THE DEFAULT SEGMENT IS SS.
; -> IN THE 8086, ONLY THE FOLLOWING BASE + INDEX COMBINATIONS ARE ALLOWED:
;       [BX+SI]
;       [BX+DI]
;       [BP+SI]
;       [BP+DI]
;=========================

MOV AX, [BP+SI]  ; BX + SI -> THE OFFSET           

       
       
;=========================
; (7) BASE + INDEX + RELATIVE ADDRESSING    

; -> THE EFFECTIVE ADDRESS (OFFSET) IS CALCULATED AS:
;    BASE REGISTER + INDEX REGISTER + DISPLACEMENT.
; -> THE DISPLACEMENT (RELATIVE VALUE) CAN BE AN 8-BIT OR 16-BIT CONSTANT.
; -> THE CPU ACCESSES THE OPERAND FROM MEMORY USING THIS OFFSET.
; -> IF BX IS THE BASE REGISTER, THE DEFAULT SEGMENT IS DS.
; -> IF BP IS THE BASE REGISTER, THE DEFAULT SEGMENT IS SS.
; -> IN THE 8086, ONLY THE FOLLOWING BASE + INDEX COMBINATIONS ARE ALLOWED:
;       [BX+SI+DISPLACEMENT]
;       [BX+DI+DISPLACEMENT]
;       [BP+SI+DISPLACEMENT]
;       [BP+DI+DISPLACEMENT]
;=========================
                                
 MOV AX, [BX + SI + 1000H] ; BX + SI + 1000H ->  THE OFFSET
                           
 

;=========================

; STACK ADDRESSING       

; -> THE OPERAND IS ACCESSED THROUGH THE STACK.
; -> THE STACK POINTER (SP) IS USED TO ACCESS THE TOP OF THE STACK.
; -> THE STACK SEGMENT (SS) IS USED BY DEFAULT.
; -> PUSH STORES DATA ONTO THE STACK.
; -> POP RETRIEVES DATA FROM THE STACK.

;=========================
                           
PUSH AX; STORE DATA INTO STACK
POP BX; RETRIEVES DATA FROM  STACK 



;=========================       

; PROGRAM (CODE) ADDRESSING MODES     

; -> USED BY CONTROL TRANSFER INSTRUCTIONS
;    (JMP, CALL, JCC, ETC.) TO CHANGE THE
;    FLOW OF PROGRAM EXECUTION.
; -> THE 8086 PROVIDES 3 TYPES OF PROGRAM
;    ADDRESSING MODES:
;    1) DIRECT ADDRESSING
;    2) INDIRECT ADDRESSING
;    3) RELATIVE ADDRESSING          

;=========================

;=========================
; DIRECT PROGRAM CODE ADDRESSING     

; -> THE TARGET ADDRESS IS SPECIFIED DIRECTLY
;    IN THE INSTRUCTION.
;=========================      

; USING JMP
JMP LABEL_NAME ; LABEL_NAME STORES  IP VALUE
MOV BX, 3

LABEL_NAME:
MOV AX, 2        

; WITHOUT USING JMP
MOV AX,  LABEL_NAME                 
JMP AX         
MOV BX, 3

LABEL_NAME:
MOV AX, 2


;=========================
; INDIRECT PROGRAM CODE ADDRESSING    

; -> THE TARGET ADDRESS (NEW IP) IS STORED
;    IN A REGISTER OR A MEMORY LOCATION.
; -> THE CPU LOADS THE TARGET ADDRESS FROM
;    THAT REGISTER OR MEMORY LOCATION.
;=========================   
 
MOV BX, 0000H
MOV [BX], LABEL_NAME ; IP -> DS MEMORY LOCATION
JMP [BX] ; DS * 10 + BX = PHYSICAL ADDRESS OF IP => CS * 10 + IP
MOV BX, 3
           
LABEL_NAME:
MOV AX, 2         
 
;=========================
; RELATIVE PROGRAM CODE ADDRESSING     

; -> THE TARGET ADDRESS IS CALCULATED BY
;    ADDING A SIGNED DISPLACEMENT TO THE
;    CURRENT IP.
;=========================

MOV BX, 0000H
MOV BX, 10H
JMP [BX + 100H]    ; BX + 100H -> THE OFFSET
MOV BX, 3

LABEL_NAME:
MOV AX, 2              


;-------------------- QUESTION --------------------

; # HOW DOES THE PROGRAM REMEMBER WHERE TO RETURN AFTER EXECUTING SOMETHING CALLED USING THE CALL FUNCTION ?
; => USING A STACK ( LAST IN FIRST OUT ). WHEN THE CALL FUNCTION CALLS A FUNCTION THE RETURN ADDRESS REMAINS STORED IN A STACK.



;=========================

; INPUT / OUTPUT ADDRESSING MODES 

; -> USED BY INPUT AND OUTPUT INSTRUCTIONS
;    (IN, OUT) TO TRANSFER DATA BETWEEN
;    THE CPU AND I/O PORTS.
; -> THE 8086 PROVIDES 2 TYPES OF
;    INPUT / OUTPUT ADDRESSING MODES:
;    1) DIRECT PORT ADDRESSING
;    2) INDIRECT PORT ADDRESSING
;
; NOTE:
; -> FOR INDIRECT PORT ADDRESSING,
;    THE PORT ADDRESS MUST BE STORED
;    IN THE DX REGISTER.
; -> DX IS THE ONLY REGISTER THAT CAN
;    HOLD THE PORT ADDRESS FOR INDIRECT
;    I/O OPERATIONS.
; -> DX IS 16-BIT, WHILE AL IS 8-BIT
;    (OR AX IS 16-BIT). THIS DOES NOT
;    CAUSE ANY PROBLEM BECAUSE DX HOLDS
;    THE PORT ADDRESS, WHEREAS AL/AX
;    HOLDS THE DATA BEING TRANSFERRED.

;=========================

; INPUT
IN AL, 05H ; 05H -> PORT ADDRESS  

; OUTPUT 
OUT DX, AL; DX DOES NOT STORE ANYTHING FROM AL, JUST STORES THE PORT ADDRESS, (UNLIKE ADD DX,AL)



;=========================

; IMPLIED ADDRESSING          

; -> THE OPERAND IS IMPLIED BY THE
;    INSTRUCTION; NO EXPLICIT OPERAND
;    IS SPECIFIED.
; -> THE CPU AUTOMATICALLY USES THE
;    REQUIRED REGISTER(S) OR FLAG(S).
;
; COMMON EXAMPLES:
; RET  : RETURNS FROM A PROCEDURE
;        (POPS THE RETURN ADDRESS FROM THE STACK)

; CLC  : CLEARS THE CARRY FLAG (CF = 0)

; STC  : SETS THE CARRY FLAG (CF = 1)

; CMC  : COMPLEMENTS (TOGGLES) THE CARRY FLAG

; HLT  : HALTS THE CPU UNTIL AN INTERRUPT
;        OR RESET OCCURS

; NOP  : NO OPERATION
;        (THE CPU DOES NOTHING FOR ONE INSTRUCTION CYCLE)

; CBW  : CONVERTS A SIGNED BYTE IN AL
;        TO A SIGNED WORD IN AX

; CWD  : CONVERTS A SIGNED WORD IN AX
;        TO A SIGNED DOUBLEWORD IN DX:AX

;=========================

RET   ; RETURN 
CLC   ; CLEAR
HLT   ; HAULT 



;=========================
; STORING AND READING A 16-BIT VALUE
;=========================
; -> THE 8086 USES LITTLE-ENDIAN BYTE ORDER.
; -> THE LOWER BYTE OF A WORD IS STORED AT THE
;    LOWER MEMORY ADDRESS.
; -> THE HIGHER BYTE IS STORED AT THE NEXT
;    MEMORY ADDRESS.
;
; EXAMPLE:
; AX = 1234H
;
; MEMORY ADDRESS      DATA
; --------------      ----
;    5000H            34H  <- LOWER BYTE (AL)
;    5001H            12H  <- HIGHER BYTE (AH)
;=========================

MOV AX, 1234H

MOV [5000H], AX      ; Stores AX into memory
                     ; [5000H] = 34H (Lower Byte)
                     ; [5001H] = 12H (Higher Byte)

MOV DX, [5000H]      ; Reads two consecutive bytes:
                     ; 34H from 5000H -> DL
                     ; 12H from 5001H -> DH
                     ; DX = 1234H

;exit to DOS
               
MOV AX,4C00H
INT 21H

MAIN ENDP
    END MAIN
